CREATE TABLE IF NOT EXISTS public.polymarket_market_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  market_slug TEXT NOT NULL,
  provider_ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  probability NUMERIC NOT NULL,
  yes_price NUMERIC,
  no_price NUMERIC,
  volume NUMERIC,
  liquidity NUMERIC,
  meta JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_polymarket_market_snapshots_slug_provider
  ON public.polymarket_market_snapshots (market_slug, provider_ts DESC);

CREATE INDEX IF NOT EXISTS idx_polymarket_market_snapshots_created_desc
  ON public.polymarket_market_snapshots (created_at DESC);

ALTER TABLE public.polymarket_market_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read on polymarket_market_snapshots" ON public.polymarket_market_snapshots;
CREATE POLICY "Allow public read on polymarket_market_snapshots"
ON public.polymarket_market_snapshots FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow service write on polymarket_market_snapshots" ON public.polymarket_market_snapshots;
CREATE POLICY "Allow service write on polymarket_market_snapshots"
ON public.polymarket_market_snapshots FOR ALL TO service_role
USING (true)
WITH CHECK (true);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.polymarket_market_snapshots;
    EXCEPTION
      WHEN duplicate_object THEN NULL;
    END;
  END IF;
END;
$$;
